name: UI Tests

on:
  workflow_dispatch:

jobs:
  ui_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Get UI Tests Repository
      uses: actions/checkout@v4    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'
        cache: 'pip'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xclip
        python -m pip install --upgrade pip &&
        ls -all &&
        pip install -r requirements.txt && playwright install-deps && playwright install

    - name: Run the automation script
      run: |
        pwd && ls -all && python -u script/sky_dev_qa_automation.py
    - name: Run debug
      if: always()
      run: |
       pwd && ls -all
    - name: Store artifact trace for distribution
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tracing
        path: trace*.zip 
        retention-days: 1      
    - name: Store videos for distribution
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: video
        path: videos/* 
        retention-days: 1      
